<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HeadFamilySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('head_family')->insert([
            'fname' => 'John',
            'lname' => 'Doe',
            'mname' => 'Smith',
            'suffix' => 'Jr.',
            'zone' => 2,
            'lot' => 1,
            'status' => 'Married',
            'phone_number' => '09123456789',
            'religion' => 'Roman Catholic',
            'birthdate' => '1990-12-25',
            'age' => 30,
            'gender' => 'Male',
            'occupation' => 'Farmer',
            'group' => 'Solo Parent',
            'four_p' => 'I\'m 4p\'s member Beneficiary',
            'gov_id' => 'Philippine Passport',
            'brgy' => 'BRGY-123-456',
            'relationship' => 'Head of Household',
            'evacuation_type' => 'Private',
            'evacuee_family_id' => 1,
        ]);

        DB::table('head_family')->insert([
            'fname' => 'Jane',
            'lname' => 'Doe',
            'mname' => 'Smith',
            'suffix' => 'N/A',
            'zone' => 2,
            'lot' => 1,
            'status' => 'Married',
            'phone_number' => '09123456789',
            'religion' => 'Roman Catholic',
            'birthdate' => '1990-12-25',
            'age' => 30,
            'gender' => 'Male',
            'occupation' => 'Farmer',
            'group' => 'Solo Parent',
            'four_p' => 'I\'m 4p\'s member Beneficiary',
            'gov_id' => 'Philippine Passport',
            'brgy' => 'BRGY-123-456',
            'relationship' => 'Head of Household',
            'evacuation_type' => 'Private',
            'evacuee_family_id' => 2,
        ]);

        DB::table('head_family')->insert([
            'fname' => 'Alice',
            'lname' => 'Smith',
            'mname' => 'Doe',
            'suffix' => 'N/A',
            'zone' => 2,
            'lot' => 1,
            'status' => 'Married',
            'phone_number' => '09123456789',
            'religion' => 'Roman Catholic',
            'birthdate' => '1990-12-25',
            'age' => 30,
            'gender' => 'Male',
            'occupation' => 'Farmer',
            'group' => 'Solo Parent',
            'four_p' => 'I\'m 4p\'s member Beneficiary',
            'gov_id' => 'Philippine Passport',
            'brgy' => 'BRGY-123-456',
            'relationship' => 'Head of Household',
            'evacuation_type' => 'Private',
            'evacuee_family_id' => 3,
        ]);

        DB::table('head_family')->insert([
            'fname' => 'Bob',
            'lname' => 'Johnson',
            'mname' => 'Reyes',
            'suffix' => 'N/A',
            'zone' => 2,
            'lot' => 1,
            'status' => 'Married',
            'phone_number' => '09123456789',
            'religion' => 'Roman Catholic',
            'birthdate' => '1990-12-25',
            'age' => 30,
            'gender' => 'Male',
            'occupation' => 'Farmer',
            'group' => 'Solo Parent',
            'four_p' => 'I\'m 4p\'s member Beneficiary',
            'gov_id' => 'Philippine Passport',
            'brgy' => 'BRGY-123-456',
            'relationship' => 'Head of Household',
            'evacuation_type' => 'Private',
            'evacuee_family_id' => 4,
        ]);

        DB::table('head_family')->insert([
            'fname' => 'Charlie',
            'lname' => 'Brown',
            'mname' => 'Reyes',
            'suffix' => 'N/A',
            'zone' => 2,
            'lot' => 1,
            'status' => 'Married',
            'phone_number' => '09123456789',
            'religion' => 'Roman Catholic',
            'birthdate' => '1990-12-25',
            'age' => 30,
            'gender' => 'Male',
            'occupation' => 'Farmer',
            'group' => 'Solo Parent',
            'four_p' => 'I\'m 4p\'s member Beneficiary',
            'gov_id' => 'Philippine Passport',
            'brgy' => 'BRGY-123-456',
            'relationship' => 'Head of Household',
            'evacuation_type' => 'Private',
            'evacuee_family_id' => 5,
        ]);

        DB::table('head_family')->insert([
            'fname' => 'David',
            'lname' => 'Clark',
            'mname' => 'Reyes',
            'suffix' => 'N/A',
            'zone' => 2,
            'lot' => 1,
            'status' => 'Married',
            'phone_number' => '09123456789',
            'religion' => 'Roman Catholic',
            'birthdate' => '1990-12-25',
            'age' => 30,
            'gender' => 'Male',
            'occupation' => 'Farmer',
            'group' => 'Solo Parent',
            'four_p' => 'I\'m 4p\'s member Beneficiary',
            'gov_id' => 'Philippine Passport',
            'brgy' => 'BRGY-123-456',
            'relationship' => 'Head of Household',
            'evacuation_type' => 'Private',
            'evacuee_family_id' => 6,
        ]);

        DB::table('head_family')->insert([
            'fname' => 'Rick',
            'lname' => 'Jayson',
            'mname' => 'Reyes',
            'suffix' => 'N/A',
            'zone' => 2,
            'lot' => 1,
            'status' => 'Married',
            'phone_number' => '09123456789',
            'religion' => 'Roman Catholic',
            'birthdate' => '1990-12-25',
            'age' => 30,
            'gender' => 'Male',
            'occupation' => 'Farmer',
            'group' => 'Solo Parent',
            'four_p' => 'I\'m 4p\'s member Beneficiary',
            'gov_id' => 'Philippine Passport',
            'brgy' => 'BRGY-123-456',
            'relationship' => 'Head of Household',
            'evacuation_type' => 'Private',
            'evacuee_family_id' => 7,
        ]);

        DB::table('head_family')->insert([
            'fname' => 'Jerome',
            'lname' => 'Brown',
            'mname' => 'Reyes',
            'suffix' => 'N/A',
            'zone' => 2,
            'lot' => 1,
            'status' => 'Married',
            'phone_number' => '09123456789',
            'religion' => 'Roman Catholic',
            'birthdate' => '1990-12-25',
            'age' => 30,
            'gender' => 'Male',
            'occupation' => 'Farmer',
            'group' => 'Solo Parent',
            'four_p' => 'I\'m 4p\'s member Beneficiary',
            'gov_id' => 'Philippine Passport',
            'brgy' => 'BRGY-123-456',
            'relationship' => 'Head of Household',
            'evacuation_type' => 'Private',
            'evacuee_family_id' => 8,
        ]);

        DB::table('head_family')->insert([
            'fname' => 'Christian',
            'lname' => 'Reyes',
            'mname' => 'Vargas',
            'suffix' => 'N/A',
            'zone' => 2,
            'lot' => 1,
            'status' => 'Married',
            'phone_number' => '09123456789',
            'religion' => 'Roman Catholic',
            'birthdate' => '1990-12-25',
            'age' => 30,
            'gender' => 'Male',
            'occupation' => 'Farmer',
            'group' => 'Solo Parent',
            'four_p' => 'I\'m 4p\'s member Beneficiary',
            'gov_id' => 'Philippine Passport',
            'brgy' => 'BRGY-123-456',
            'relationship' => 'Head of Household',
            'evacuation_type' => 'Private',
            'evacuee_family_id' => 9,
        ]);
    }
}
