<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MembersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('members')->insert([
            'fname' => 'Carlos',
            'lname' => 'Gomez',
            'mname' => 'Lopez',
            'suffix' => 'Sr.',
            'zone' => 3,
            'lot' => 12,
            'status' => 'Married',
            'phone_number' => '09129876543',
            'religion' => 'Christian',
            'birthdate' => '1985-08-15',
            'age' => 39,
            'gender' => 'Male',
            'occupation' => 'Engineer',
            'group' => 'N/A',
            'relationship' => 'Head of Household',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 1,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 1,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Maria',
            'lname' => 'Gomez',
            'mname' => 'Rivera',
            'suffix' => 'N/A',
            'zone' => 3,
            'lot' => 12,
            'status' => 'Married',
            'phone_number' => '09129876544',
            'religion' => 'Christian',
            'birthdate' => '1987-11-22',
            'age' => 37,
            'gender' => 'Female',
            'occupation' => 'Teacher',
            'group' => 'N/A',
            'relationship' => 'Spouse',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 1,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 1,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Luis',
            'lname' => 'Gomez',
            'mname' => 'Lopez',
            'suffix' => 'Jr.',
            'zone' => 3,
            'lot' => 12,
            'status' => 'Single',
            'phone_number' => '09129876545',
            'religion' => 'Christian',
            'birthdate' => '2010-05-10',
            'age' => 14,
            'gender' => 'Male',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 1,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 1,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Sofia',
            'lname' => 'Gomez',
            'mname' => 'Lopez',
            'suffix' => 'N/A',
            'zone' => 3,
            'lot' => 12,
            'status' => 'Single',
            'phone_number' => '09129876546',
            'religion' => 'Christian',
            'birthdate' => '2016-09-30',
            'age' => 8,
            'gender' => 'Female',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 1,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 1,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Daniel',
            'lname' => 'Martinez',
            'mname' => 'Santos',
            'suffix' => 'N/A',
            'zone' => 5,
            'lot' => 8,
            'status' => 'Married',
            'phone_number' => '09127654321',
            'religion' => 'Catholic',
            'birthdate' => '1982-03-18',
            'age' => 42,
            'gender' => 'Male',
            'occupation' => 'Carpenter',
            'group' => 'N/A',
            'relationship' => 'Head of Household',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 1,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 2,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Isabel',
            'lname' => 'Martinez',
            'mname' => 'Gonzalez',
            'suffix' => 'N/A',
            'zone' => 5,
            'lot' => 8,
            'status' => 'Married',
            'phone_number' => '09127654322',
            'religion' => 'Catholic',
            'birthdate' => '1985-07-12',
            'age' => 39,
            'gender' => 'Female',
            'occupation' => 'Nurse',
            'group' => 'N/A',
            'relationship' => 'Spouse',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 1,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 2,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Miguel',
            'lname' => 'Martinez',
            'mname' => 'Santos',
            'suffix' => 'N/A',
            'zone' => 5,
            'lot' => 8,
            'status' => 'Single',
            'phone_number' => '09127654323',
            'religion' => 'Catholic',
            'birthdate' => '2012-11-25',
            'age' => 12,
            'gender' => 'Male',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 1,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 2,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Elena',
            'lname' => 'Martinez',
            'mname' => 'Santos',
            'suffix' => 'N/A',
            'zone' => 5,
            'lot' => 8,
            'status' => 'Single',
            'phone_number' => '09127654324',
            'religion' => 'Catholic',
            'birthdate' => '2019-02-10',
            'age' => 5,
            'gender' => 'Female',
            'occupation' => 'N/A',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 1,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 2,
            'evacuation_center_id' => null,
        ]);

        DB::table('members')->insert([
            'fname' => 'Roberto',
            'lname' => 'Delacruz',
            'mname' => 'Fernandez',
            'suffix' => 'N/A',
            'zone' => 7,
            'lot' => 15,
            'status' => 'Married',
            'phone_number' => '09124567890',
            'religion' => 'Catholic',
            'birthdate' => '1980-06-05',
            'age' => 44,
            'gender' => 'Male',
            'occupation' => 'Electrician',
            'group' => 'N/A',
            'relationship' => 'Head of Household',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 1,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 3,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Carmen',
            'lname' => 'Delacruz',
            'mname' => 'Lopez',
            'suffix' => 'N/A',
            'zone' => 7,
            'lot' => 15,
            'status' => 'Married',
            'phone_number' => '09124567891',
            'religion' => 'Catholic',
            'birthdate' => '1983-09-12',
            'age' => 41,
            'gender' => 'Female',
            'occupation' => 'Vendor',
            'group' => 'N/A',
            'relationship' => 'Spouse',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 1,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 3,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Emmanuel',
            'lname' => 'Delacruz',
            'mname' => 'Fernandez',
            'suffix' => 'N/A',
            'zone' => 7,
            'lot' => 15,
            'status' => 'Single',
            'phone_number' => '09124567892',
            'religion' => 'Catholic',
            'birthdate' => '2008-03-20',
            'age' => 16,
            'gender' => 'Male',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 1,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 3,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Isabela',
            'lname' => 'Delacruz',
            'mname' => 'Fernandez',
            'suffix' => 'N/A',
            'zone' => 7,
            'lot' => 15,
            'status' => 'Single',
            'phone_number' => '09124567893',
            'religion' => 'Catholic',
            'birthdate' => '2012-07-08',
            'age' => 12,
            'gender' => 'Female',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 1,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 3,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Santiago',
            'lname' => 'Delacruz',
            'mname' => 'Fernandez',
            'suffix' => 'N/A',
            'zone' => 7,
            'lot' => 15,
            'status' => 'Single',
            'phone_number' => '09124567894',
            'religion' => 'Catholic',
            'birthdate' => '2017-05-14',
            'age' => 7,
            'gender' => 'Male',
            'occupation' => 'N/A',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 1,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 3,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Lucia',
            'lname' => 'Delacruz',
            'mname' => 'Fernandez',
            'suffix' => 'N/A',
            'zone' => 7,
            'lot' => 15,
            'status' => 'Single',
            'phone_number' => '09124567895',
            'religion' => 'Catholic',
            'birthdate' => '2022-10-22',
            'age' => 2,
            'gender' => 'Female',
            'occupation' => 'N/A',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 1,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 3,
            'evacuation_center_id' => null,
        ]);
         
        DB::table('members')->insert([
            'fname' => 'Miguel',
            'lname' => 'Santiago',
            'mname' => 'Ramirez',
            'suffix' => 'N/A',
            'zone' => 3,
            'lot' => 10,
            'status' => 'Married',
            'phone_number' => '09129876543',
            'religion' => 'Catholic',
            'birthdate' => '1985-11-15',
            'age' => 39,
            'gender' => 'Male',
            'occupation' => 'Driver',
            'group' => 'N/A',
            'relationship' => 'Head of Household',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 1,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 4,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Angela',
            'lname' => 'Santiago',
            'mname' => 'Reyes',
            'suffix' => 'N/A',
            'zone' => 3,
            'lot' => 10,
            'status' => 'Married',
            'phone_number' => '09129876544',
            'religion' => 'Catholic',
            'birthdate' => '1988-04-22',
            'age' => 36,
            'gender' => 'Female',
            'occupation' => 'Teacher',
            'group' => 'N/A',
            'relationship' => 'Spouse',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 1,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 4,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Carlos',
            'lname' => 'Santiago',
            'mname' => 'Ramirez',
            'suffix' => 'N/A',
            'zone' => 3,
            'lot' => 10,
            'status' => 'Single',
            'phone_number' => '09129876545',
            'religion' => 'Catholic',
            'birthdate' => '2015-09-30',
            'age' => 9,
            'gender' => 'Male',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 1,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 4,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Eduardo',
            'lname' => 'Gomez',
            'mname' => 'Santos',
            'suffix' => 'N/A',
            'zone' => 5,
            'lot' => 20,
            'status' => 'Married',
            'phone_number' => '09127654321',
            'religion' => 'Catholic',
            'birthdate' => '1982-02-18',
            'age' => 43,
            'gender' => 'Male',
            'occupation' => 'Carpenter',
            'group' => 'N/A',
            'relationship' => 'Head of Household',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 1,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 5,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Maria',
            'lname' => 'Gomez',
            'mname' => 'Lopez',
            'suffix' => 'N/A',
            'zone' => 5,
            'lot' => 20,
            'status' => 'Married',
            'phone_number' => '09127654322',
            'religion' => 'Catholic',
            'birthdate' => '1985-06-25',
            'age' => 39,
            'gender' => 'Female',
            'occupation' => 'Housewife',
            'group' => 'N/A',
            'relationship' => 'Spouse',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 1,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 5,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Gabriel',
            'lname' => 'Gomez',
            'mname' => 'Santos',
            'suffix' => 'N/A',
            'zone' => 5,
            'lot' => 20,
            'status' => 'Single',
            'phone_number' => '09127654323',
            'religion' => 'Catholic',
            'birthdate' => '2007-08-12',
            'age' => 17,
            'gender' => 'Male',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 1,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 5,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Elena',
            'lname' => 'Gomez',
            'mname' => 'Santos',
            'suffix' => 'N/A',
            'zone' => 5,
            'lot' => 20,
            'status' => 'Single',
            'phone_number' => '09127654324',
            'religion' => 'Catholic',
            'birthdate' => '2010-11-03',
            'age' => 14,
            'gender' => 'Female',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 1,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 5,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Ricardo',
            'lname' => 'Gomez',
            'mname' => 'Santos',
            'suffix' => 'N/A',
            'zone' => 5,
            'lot' => 20,
            'status' => 'Single',
            'phone_number' => '09127654325',
            'religion' => 'Catholic',
            'birthdate' => '2015-04-27',
            'age' => 9,
            'gender' => 'Male',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 1,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 5,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Sofia',
            'lname' => 'Gomez',
            'mname' => 'Santos',
            'suffix' => 'N/A',
            'zone' => 5,
            'lot' => 20,
            'status' => 'Single',
            'phone_number' => '09127654326',
            'religion' => 'Catholic',
            'birthdate' => '2018-02-14',
            'age' => 6,
            'gender' => 'Female',
            'occupation' => 'N/A',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 1,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 5,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Lorenzo',
            'lname' => 'Gomez',
            'mname' => 'Santos',
            'suffix' => 'N/A',
            'zone' => 5,
            'lot' => 20,
            'status' => 'Single',
            'phone_number' => '09127654327',
            'religion' => 'Catholic',
            'birthdate' => '2022-07-09',
            'age' => 2,
            'gender' => 'Male',
            'occupation' => 'N/A',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 1,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 5,
            'evacuation_center_id' => null,
        ]);
        DB::table('members')->insert([
            'fname' => 'Roberto',
            'lname' => 'Delacruz',
            'mname' => 'Fernandez',
            'suffix' => 'N/A',
            'zone' => 6,
            'lot' => 15,
            'status' => 'Married',
            'phone_number' => '09123456788',
            'religion' => 'Catholic',
            'birthdate' => '1980-03-10',
            'age' => 44,
            'gender' => 'Male',
            'occupation' => 'Fisherman',
            'group' => 'N/A',
            'relationship' => 'Head of Household',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 1,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 6,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Isabel',
            'lname' => 'Delacruz',
            'mname' => 'Morales',
            'suffix' => 'N/A',
            'zone' => 6,
            'lot' => 15,
            'status' => 'Married',
            'phone_number' => '09123456787',
            'religion' => 'Catholic',
            'birthdate' => '1983-09-25',
            'age' => 40,
            'gender' => 'Female',
            'occupation' => 'Vendor',
            'group' => 'N/A',
            'relationship' => 'Spouse',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 1,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 6,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Mark',
            'lname' => 'Delacruz',
            'mname' => 'Fernandez',
            'suffix' => 'N/A',
            'zone' => 6,
            'lot' => 15,
            'status' => 'Single',
            'phone_number' => '09123456786',
            'religion' => 'Catholic',
            'birthdate' => '2006-05-14',
            'age' => 18,
            'gender' => 'Male',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 1,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 6,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Samantha',
            'lname' => 'Delacruz',
            'mname' => 'Fernandez',
            'suffix' => 'N/A',
            'zone' => 6,
            'lot' => 15,
            'status' => 'Single',
            'phone_number' => '09123456785',
            'religion' => 'Catholic',
            'birthdate' => '2010-07-08',
            'age' => 14,
            'gender' => 'Female',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 1,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 6,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Luis',
            'lname' => 'Delacruz',
            'mname' => 'Fernandez',
            'suffix' => 'N/A',
            'zone' => 6,
            'lot' => 15,
            'status' => 'Single',
            'phone_number' => '09123456784',
            'religion' => 'Catholic',
            'birthdate' => '2015-12-02',
            'age' => 9,
            'gender' => 'Male',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 1,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 6,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Sofia',
            'lname' => 'Delacruz',
            'mname' => 'Fernandez',
            'suffix' => 'N/A',
            'zone' => 6,
            'lot' => 15,
            'status' => 'Single',
            'phone_number' => '09123456783',
            'religion' => 'Catholic',
            'birthdate' => '2021-03-15',
            'age' => 3,
            'gender' => 'Female',
            'occupation' => 'N/A',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 1,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 6,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Antonio',
            'lname' => 'Gonzales',
            'mname' => 'Ramos',
            'suffix' => 'N/A',
            'zone' => 7,
            'lot' => 20,
            'status' => 'Married',
            'phone_number' => '09123456782',
            'religion' => 'Catholic',
            'birthdate' => '1978-01-15',
            'age' => 46,
            'gender' => 'Male',
            'occupation' => 'Carpenter',
            'group' => 'N/A',
            'relationship' => 'Head of Household',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 1,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 7,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Maria',
            'lname' => 'Gonzales',
            'mname' => 'Rivera',
            'suffix' => 'N/A',
            'zone' => 7,
            'lot' => 20,
            'status' => 'Married',
            'phone_number' => '09123456781',
            'religion' => 'Catholic',
            'birthdate' => '1980-06-30',
            'age' => 44,
            'gender' => 'Female',
            'occupation' => 'Housewife',
            'group' => 'N/A',
            'relationship' => 'Spouse',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 1,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 7,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Daniel',
            'lname' => 'Gonzales',
            'mname' => 'Ramos',
            'suffix' => 'N/A',
            'zone' => 7,
            'lot' => 20,
            'status' => 'Single',
            'phone_number' => '09123456780',
            'religion' => 'Catholic',
            'birthdate' => '2004-09-05',
            'age' => 20,
            'gender' => 'Male',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 1,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 7,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Andrea',
            'lname' => 'Gonzales',
            'mname' => 'Ramos',
            'suffix' => 'N/A',
            'zone' => 7,
            'lot' => 20,
            'status' => 'Single',
            'phone_number' => '09123456779',
            'religion' => 'Catholic',
            'birthdate' => '2008-04-12',
            'age' => 16,
            'gender' => 'Female',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 1,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 7,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Gabriel',
            'lname' => 'Gonzales',
            'mname' => 'Ramos',
            'suffix' => 'N/A',
            'zone' => 7,
            'lot' => 20,
            'status' => 'Single',
            'phone_number' => '09123456778',
            'religion' => 'Catholic',
            'birthdate' => '2012-11-20',
            'age' => 12,
            'gender' => 'Male',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 1,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 7,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Sophia',
            'lname' => 'Gonzales',
            'mname' => 'Ramos',
            'suffix' => 'N/A',
            'zone' => 7,
            'lot' => 20,
            'status' => 'Single',
            'phone_number' => '09123456777',
            'religion' => 'Catholic',
            'birthdate' => '2018-07-28',
            'age' => 6,
            'gender' => 'Female',
            'occupation' => 'N/A',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 1,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 7,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Lucas',
            'lname' => 'Gonzales',
            'mname' => 'Ramos',
            'suffix' => 'N/A',
            'zone' => 7,
            'lot' => 20,
            'status' => 'Single',
            'phone_number' => '09123456776',
            'religion' => 'Catholic',
            'birthdate' => '2022-01-10',
            'age' => 2,
            'gender' => 'Male',
            'occupation' => 'N/A',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 1,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 7,
            'evacuation_center_id' => null,
        ]);
         
        DB::table('members')->insert([
            'fname' => 'Carlos',
            'lname' => 'Dela Cruz',
            'mname' => 'Santos',
            'suffix' => 'N/A',
            'zone' => 8,
            'lot' => 15,
            'status' => 'Married',
            'phone_number' => '09123456785',
            'religion' => 'Catholic',
            'birthdate' => '1982-03-10',
            'age' => 42,
            'gender' => 'Male',
            'occupation' => 'Fisherman',
            'group' => 'N/A',
            'relationship' => 'Head of Household',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 1,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 8,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Isabel',
            'lname' => 'Dela Cruz',
            'mname' => 'Garcia',
            'suffix' => 'N/A',
            'zone' => 8,
            'lot' => 15,
            'status' => 'Married',
            'phone_number' => '09123456784',
            'religion' => 'Catholic',
            'birthdate' => '1985-07-25',
            'age' => 39,
            'gender' => 'Female',
            'occupation' => 'Vendor',
            'group' => 'N/A',
            'relationship' => 'Spouse',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 1,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 8,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Miguel',
            'lname' => 'Dela Cruz',
            'mname' => 'Santos',
            'suffix' => 'N/A',
            'zone' => 8,
            'lot' => 15,
            'status' => 'Single',
            'phone_number' => '09123456783',
            'religion' => 'Catholic',
            'birthdate' => '2006-05-18',
            'age' => 18,
            'gender' => 'Male',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 1,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 8,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Ana',
            'lname' => 'Dela Cruz',
            'mname' => 'Santos',
            'suffix' => 'N/A',
            'zone' => 8,
            'lot' => 15,
            'status' => 'Single',
            'phone_number' => '09123456782',
            'religion' => 'Catholic',
            'birthdate' => '2009-10-22',
            'age' => 15,
            'gender' => 'Female',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 1,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 8,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Paolo',
            'lname' => 'Dela Cruz',
            'mname' => 'Santos',
            'suffix' => 'N/A',
            'zone' => 8,
            'lot' => 15,
            'status' => 'Single',
            'phone_number' => '09123456781',
            'religion' => 'Catholic',
            'birthdate' => '2013-09-30',
            'age' => 11,
            'gender' => 'Male',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 1,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 8,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Elena',
            'lname' => 'Dela Cruz',
            'mname' => 'Santos',
            'suffix' => 'N/A',
            'zone' => 8,
            'lot' => 15,
            'status' => 'Single',
            'phone_number' => '09123456780',
            'religion' => 'Catholic',
            'birthdate' => '2017-12-12',
            'age' => 7,
            'gender' => 'Female',
            'occupation' => 'N/A',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 1,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 8,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Lucas',
            'lname' => 'Dela Cruz',
            'mname' => 'Santos',
            'suffix' => 'N/A',
            'zone' => 8,
            'lot' => 15,
            'status' => 'Single',
            'phone_number' => '09123456779',
            'religion' => 'Catholic',
            'birthdate' => '2021-05-02',
            'age' => 3,
            'gender' => 'Male',
            'occupation' => 'N/A',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 1,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 8,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Rafael',
            'lname' => 'Gonzalez',
            'mname' => 'Lopez',
            'suffix' => 'N/A',
            'zone' => 9,
            'lot' => 20,
            'status' => 'Married',
            'phone_number' => '09123456778',
            'religion' => 'Catholic',
            'birthdate' => '1988-06-15',
            'age' => 36,
            'gender' => 'Male',
            'occupation' => 'Carpenter',
            'group' => 'N/A',
            'relationship' => 'Head of Household',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 1,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 9,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Maria',
            'lname' => 'Gonzalez',
            'mname' => 'Cruz',
            'suffix' => 'N/A',
            'zone' => 9,
            'lot' => 20,
            'status' => 'Married',
            'phone_number' => '09123456777',
            'religion' => 'Catholic',
            'birthdate' => '1990-02-22',
            'age' => 34,
            'gender' => 'Female',
            'occupation' => 'Housewife',
            'group' => 'N/A',
            'relationship' => 'Spouse',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 1,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 9,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Javier',
            'lname' => 'Gonzalez',
            'mname' => 'Lopez',
            'suffix' => 'N/A',
            'zone' => 9,
            'lot' => 20,
            'status' => 'Single',
            'phone_number' => '09123456776',
            'religion' => 'Catholic',
            'birthdate' => '2012-09-10',
            'age' => 12,
            'gender' => 'Male',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 1,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 9,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Elena',
            'lname' => 'Gonzalez',
            'mname' => 'Lopez',
            'suffix' => 'N/A',
            'zone' => 9,
            'lot' => 20,
            'status' => 'Single',
            'phone_number' => '09123456775',
            'religion' => 'Catholic',
            'birthdate' => '2016-04-18',
            'age' => 8,
            'gender' => 'Female',
            'occupation' => 'Student',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 0,
            'toddlers' => 0,
            'preschool' => 1,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 9,
            'evacuation_center_id' => null,
        ]);
        
        DB::table('members')->insert([
            'fname' => 'Mateo',
            'lname' => 'Gonzalez',
            'mname' => 'Lopez',
            'suffix' => 'N/A',
            'zone' => 9,
            'lot' => 20,
            'status' => 'Single',
            'phone_number' => '09123456774',
            'religion' => 'Catholic',
            'birthdate' => '2021-07-05',
            'age' => 3,
            'gender' => 'Male',
            'occupation' => 'N/A',
            'group' => 'N/A',
            'relationship' => 'Child',
            'infant' => 1,
            'toddlers' => 0,
            'preschool' => 0,
            'schoolAge' => 0,
            'teenAge' => 0,
            'adult' => 0,
            'seniorCitizen' => 0,
            'lactatingMothers' => 0,
            'pregnant' => 0,
            'pwd' => 0,
            'soloParent' => 0,
            'head_id' => 9,
            'evacuation_center_id' => null,
        ]);
    }
}
